### ISSUE TITLE
Impossible To Setup

### ISSUE THREAD

**Issue by Tkdriverx** [Jaex/Automate#1]
I am having so many issues trying to compile/set up this program. Please make an easy to use .exe setup or explain to me how to set this up.

Thanks.

**Comment by Jaex** [comment]
What you mean easy to use .exe setup? Is current setup difficult to use in here? https://github.com/Jaex/Automate/releases

**Comment by Tkdriverx** [comment]
I didn't see the releases page, sorry to bother you. I'm kind of a noob when it comes to GitHub. :(
